import fetch from 'isomorphic-unfetch';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home(props) {
  const { data = [] } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Jamstack!</h1>
        <p>
          Please go to{' '}
          <a href="https://github.com/ycjcl868/jamstack/issues">
            https://github.com/ycjcl868/jamstack/issues
          </a>
        </p>

        <div className={styles.grid}>
          {data?.length === 0 ? (
            <p>Empty issues</p>
          ) : (
            data?.map((item) => {
              return (
                <a
                  key={`${item.id}`}
                  href="https://nextjs.org/docs"
                  className={styles.card}
                >
                  <h2>{item.title}</h2>
                  <p>Created by {item.user.login}</p>
                </a>
              );
            })
          )}
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    'https://api.github.com/repos/ycjcl868/jamstack/issues',
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data, // will be passed to the page component as props}
    },
  };
};
