import fetch from 'isomorphic-unfetch';
import Head from 'next/head';
import ReactUtterances from '../components/ReactUtterances';
import styles from '../styles/Home.module.css';

export default function Home(props) {
  const { data = [] } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Jamstack!</h1>
        <p>
          Please go to{' '}
          <a href="https://github.com/ycjcl868/jamstack/issues">
            https://github.com/ycjcl868/jamstack/issues
          </a>
        </p>

        <div className={styles.grid}>
          {data?.length === 0 ? (
            <p>Empty issues</p>
          ) : (
            data?.map((item) => {
              return (
                <a
                  key={`${item.id}`}
                  href={item.html_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={styles.card}
                >
                  <h2>{item.title}</h2>
                </a>
              );
            })
          )}
        </div>
        <footer className={styles.footer}>
          <ReactUtterances
            repo="ycjcl868/jamstack"
            issueMap="issue-term"
            issueTerm="title"
            theme={'github-light'}
          />
        </footer>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    'https://api.github.com/repos/ycjcl868/jamstack/issues?state=open',
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data, // will be passed to the page component as props}
    },
    revalidate: 1,
  };
};
